[service]
service_name = "user-web"
service_tags = ["web", "imooc"]
host = "192.168.3.56"
port = 8021

[client.user-srv]
host = "127.0.0.1"
port = 8083

[log]
level = "debug"
file_path = "storage/service.log"

[jwt]
key = "5WVdD8p2n^aK4MQv"

[sms]
key = "LTAI5tS48rUWjkPgF1ipmtLh"
secret = "kqyga30aoxpuKs2FPMJB0nsM15DPX0"

[redis]
host = "127.0.0.1"
port = 6379

[consul]
host = "127.0.0.1"
port = 8500